export const DOCUMENT_STORAGE = Symbol("DOCUMENT_STORAGE");
export const DOCUMENT_REPOSITORY = Symbol("DOCUMENT_REPOSITORY");
export const OCR_ADAPTER = Symbol("OCR_ADAPTER");
export const BARCODE_ADAPTER = Symbol("BARCODE_ADAPTER");
export const STRUCTURED_EXTRACTION_ADAPTER = Symbol("STRUCTURED_EXTRACTION_ADAPTER");
export const REDACTION_ADAPTER = Symbol("REDACTION_ADAPTER");
export const DOCUMENT_PROCESSING_QUEUE = Symbol("DOCUMENT_PROCESSING_QUEUE");
